feat: introduce LayoutClickEvent feature
vaadin/flow-legacy-components pull request #103
Opened 2021-10-12 08:49 UTC by pleku

Introduces legacy LayouClickEvent feature which is based on low-level
Element API feature in Flow 9.0. This means that this project cannot be
used on top of Vaadin < 22 for now.

Closes #25

2021-10-13 08:36 UTC, DiegoCardoso commented on vaadin-legacy-components-flow-integration-tests/src/test/java/com/vaadin/legacy/ui/test/LayoutClickListenerIT.java
> +    public void layoutClickListenerOnLayout_whenClickedInsideChildComponentInternalStructure_reportsCorrectClickedComponentClass() {
From the name of this method, I thought the test was trying to perform a click on an internal element of a component (like the slot or spacing from an ordered layout), but it's clicking on the layout itself only. 
I guess we can have it tested that clicking on an internal element that doesn't map to a component will report the correct component as clicked.

2021-10-13 08:40 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        if (clickedComponent
I tried to quickly use the same approach as done with the `Scroller` component on `Panel` to see if we could get rid of this, but it didn't work well on my first try. But I believe this would be the preferred way to use the `VLabel` on `Label` and it can be covered by another issue.

2021-11-19 13:54 UTC, pleku commented on vaadin-legacy-components-flow-integration-tests/src/test/java/com/vaadin/legacy/ui/test/LayoutClickListenerIT.java
> +    public void layoutClickListenerOnLayout_whenClickedInsideChildComponentInternalStructure_reportsCorrectClickedComponentClass() {
Done

2021-11-19 13:56 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        if (clickedComponent
This is validated now at least with Label & slots

2021-11-19 13:56 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/event/MouseEvents.java
> +    public static class ClickEvent extends ComponentEvent<Component> {
Done

2021-11-19 13:56 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/event/MouseEvents.java
> +        public int getRelativeX() {
Adopted

2021-11-22 11:26 UTC, fhdhsni requested changes

2021-11-22 12:11 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +import elemental.json.JsonObject;
Fixed

2021-11-22 12:11 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/event/MouseEvents.java
> +            Helpers.logUnsupportedApiCall(getClass(), "getRelativeY()");
Fixed

2021-11-22 12:11 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/event/MouseEvents.java
> +            Helpers.logUnsupportedApiCall(getClass(), "getRelativeX()");
Fixed

2021-11-22 12:28 UTC, fhdhsni approved these changes

2021-11-22 14:30 UTC, merged