fix: add `v-lcp` CSS class to all LCP components
vaadin/flow-legacy-components pull request #114
Opened 2021-11-17 11:10 UTC by DiegoCardoso

## Description

To avoid styling conflicts when LCP is used alongside V8/V7 components with MPR, this change adds a custom CSS class to all LCP components and updates the CSS selectors to be prefixed with the class.

Fixes #111

## Type of change

- Bugfix

2021-11-17 16:45 UTC, fhdhsni requested changes

2021-11-17 16:45 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/resources/META-INF/frontend/panel.css
> +.v-lcp .v-panel-borderless {
should be `.v-lcp.v-panel-borderless`
also the rest of the panel theme class names bellow. (`.v-lcp.v-panel-something`)

2021-11-18 09:01 UTC, fhdhsni approved these changes

2021-11-18 09:02 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/resources/META-INF/frontend/panel.css
> +.v-lcp .v-panel-borderless {
Done.

2021-11-18 09:02 UTC, merged