[WIP] feat: create DOM structure
vaadin/flow-legacy-components pull request #33
Opened 2021-09-08 07:14 UTC by fhdhsni

fixes #6
fixes #19

2021-09-08 09:25 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +    public void addComponents(Component... newComponents) {
In legacy FW this API is exposed at `AbstractComponentContainer` level, so that is the reasoning for exposing it here ?

I think it might make sense to keep the code structure the same as much as possible, and then move new parts that do some additional things like something that was previously done on the client side, like creating a slot or update spacing, as their own isolated private methods.

The legacy part has for example `componentAdded` and `componentRemoved` which manages the alignment data for the component and it is triggered from any of the methods.

2021-09-08 09:25 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +    public void setSpacing(boolean spacing) {
Would it make sense to have the spacing just first on/off and then later on introduce the API and tests for controlling it so that the PR doesn't grow in size and complexity? It is easier at least to review when focusing just on one aspect. Could reduce cycle time

2021-09-09 06:01 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractComponentContainer.java
> +        }
just to align with the way [framework](https://github.com/vaadin/framework/blob/e30226a19564c6ee77064e5178a7665554d57466/server/src/main/java/com/vaadin/ui/AbstractComponentContainer.java#L54-L59) works

2021-09-09 07:26 UTC, pleku requested changes
Is there still something else remaining as this is still marked as WIP ?

2021-09-09 07:26 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +import com.vaadin.flow.component.*;
The coding conventions prohibit wildcard imports, you should setup your IDE to not include those (for testing doesn't matter)

2021-09-09 07:26 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            super.add(slot);
There is a problem now that as the slots are components themselves (like the wrapper too), the flow specific API for e.g. `getChildren` will return either the wrapper or the slots, instead of whatever was set with `addComponent`. Neither the slot components or the wrapper should be exposed to outside as those are "implementation details".

The simple solution would be to just override `getChildren` and instead have it return the internal elements, but I'm not sure if that is enough to keep everything working.
Another solution would be to use elements instead of components for the wrapper and slots.

2021-09-09 07:26 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/ComponentContainer.java
> +    default Stream<Component> getComponents() {
Non-blocking: This would be new API to the legacy components. I understand that it is for "our convenience" but it is not really necessary as we're going to have to include the iterator API too

2021-09-09 13:20 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/ComponentContainer.java
> +    default Stream<Component> getComponents() {
will remove it after introducing iterators
https://github.com/vaadin/flow-legacy-components/issues/36

2021-09-09 13:20 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +import com.vaadin.flow.component.*;
done

2021-09-09 13:27 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/resources/META-INF/frontend/styles.css
> +.v-expand {
done

2021-09-09 13:28 UTC, fhdhsni commented on vaadin-legacy-components-flow-integration-tests/src/main/java/com/vaadin/legacy/ui/examples/AbstractOrderedLayoutView.java
> +public class AbstractOrderedLayoutView extends Div {
removed the `HorizontalLayout` and tested for both vertical/horizontal orientation.

2021-09-09 13:29 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +    public AbstractOrderedLayout(boolean isVertical) {
c/p from the FW. please check to see if it suffices

2021-09-09 13:33 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            super.add(slot);
couldn't find anyway other than `getChildren` to get the inner components (besides `getElement`) so overriding `getChildren` seems enough.

2021-09-10 07:17 UTC, pleku approved these changes

2021-09-10 07:33 UTC, merged