add v-spacing between components
vaadin/flow-legacy-components pull request #41
Opened 2021-09-10 13:29 UTC by fhdhsni

fixes #19

2021-09-10 13:53 UTC, fhdhsni commented
got the default spacing wrong 🤦‍♂️

2021-09-13 08:04 UTC, pleku requested changes

2021-09-13 08:04 UTC, pleku commented on vaadin-legacy-components-flow/src/test/java/com/vaadin/legacy/ui/AbstractOrderedLayoutTest.java
> +        Assert.assertEquals(0, countSpacingElements(layout));
Missing test for adding/removing a component at/from the beginning, so that should probably be included in #10

2021-09-13 11:03 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +    /**
added a small description. see if it's enough.
[the FW javadocs](https://github.com/vaadin/framework/blob/master/server/src/main/java/com/vaadin/ui/Layout.java#L111-L115)

2021-09-13 11:03 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            boolean isNotTheFirstComponent = components.size() != 0;
done

2021-09-13 11:04 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +                if (!this.components.containsValue(spacingComponent)) {
Forgot to update this after changing the logic.

Done.

2021-09-13 11:04 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +    private List<Component> getChildComponents() {
yeah, let's improve this after moving to Element API

2021-09-13 11:04 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            maybeSpacingElement.getComponent().ifPresent(spacingComponent -> {
done

2021-09-13 11:04 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            } else if (isSpacing) {
used two separate methods as suggested by the next comment

2021-09-13 11:04 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +    private void toggleSpacingElements() {
done

2021-09-13 11:05 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        Div div = new Div();
Let's fix it with #42, added a TODO

2021-09-13 11:05 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/resources/META-INF/frontend/ordered-layout.css
> +    width: 12px;
C/P from the FW just in case

2021-09-13 11:05 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/resources/META-INF/frontend/ordered-layout.css
> +    width: 0;
since we're using flex, float and clear have no effect.

2021-09-13 11:05 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/test/java/com/vaadin/legacy/ui/AbstractOrderedLayoutTest.java
> +        target.setSpacing(true);
no reason, removed it to align with other tests

2021-09-13 11:05 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/test/java/com/vaadin/legacy/ui/AbstractOrderedLayoutTest.java
> +        Assert.assertEquals(0, countSpacingElements(layout));
added a test for removing from the beginning. Test for adding a component at the beginning will be added with #10

2021-09-13 11:44 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/resources/META-INF/frontend/ordered-layout.css
> +    width: 12px;
> My CSS is not great, but isn't it possible that it would be more difficult to override the width/height because there are two selectors used here ? 

Yes, it would make the selector more specific than just `.v-spacing`.

2021-09-13 18:38 UTC, pleku reviewed
LGTM but I might want to land #47 first and then I could rebase this one on top of that - there will be merge conflicts but I can take care of those

2021-09-13 18:38 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +    /**
right, there is no javadocs in FW either 🤦🏻‍♂️

2021-09-13 18:38 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        Div div = new Div();
Lets see tomorrow which one we'll land first. I could fix this one if #47 is landed first

2021-09-14 14:08 UTC, pleku reviewed
This is fine, but as I've touched it, I should not approve it

2021-09-14 14:09 UTC, pleku approved these changes

2021-09-14 14:42 UTC, DiegoCardoso approved these changes
There's only one small suggestion, but otherwise LGTM

2021-09-14 14:42 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +                    int index = container.indexOfChild(slot);
nit: for the sake of clarity, should this variable be renamed to something more meaningful?

2021-09-15 05:43 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +                    int index = container.indexOfChild(slot);
I don't like the name `somethingMoreMeaningful` :trollface:  but I tried to make it more obvious

2021-09-15 06:01 UTC, DiegoCardoso approved these changes

2021-09-15 06:01 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +                    int index = container.indexOfChild(slot);
I am glad you were able to find another thing more meaningful to use there 😂

2021-09-15 06:14 UTC, merged