feat: add expand ratio API
vaadin/flow-legacy-components pull request #53
Opened 2021-09-16 10:27 UTC by DiegoCardoso

## Description

Add expand ratio getter and setter for components inside an `AbstractOrderedLayout`.

- methods throws if component is not a child of the layout
- `setExpandRatio` also do not allow values lower than zero
- update styles to use `flex-basis: 0` so it will not count the intrinsic size of the child when distributing the spaces
- hook the logic to set expand ratio to slots on `beforeClientResponse` lifecycle callback and on the detach listener added to components
- add unit and integration tests

Fixes # #22 

## Type of change

- [ ] Bugfix
- [x] Feature

2021-09-16 10:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow-legacy-components?pullRequest=53) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow-legacy-components?pullRequest=53) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow-legacy-components?pullRequest=53) it.</sub>

2021-09-16 18:10 UTC, pleku requested changes
Can't fault it, but would like to see one added unit test

2021-09-16 18:10 UTC, pleku commented on vaadin-legacy-components-flow/src/test/java/com/vaadin/legacy/ui/AbstractOrderedLayoutTest.java
> +
What about testing that when the last component that had expand ratio is removed (via API or via element API (e.g. external)), then things are "recalculated"

2021-09-16 18:10 UTC, pleku commented on vaadin-legacy-components-flow-integration-tests/src/main/java/com/vaadin/legacy/ui/examples/layout/layouttester/ExpandRatioView.java
> +                "Set expand ratio (one)",
The caption says "(one)" but it sets two ?

2021-09-17 07:34 UTC, pleku commented
What about `addComponentAndExpand`

2021-09-17 11:32 UTC, DiegoCardoso reviewed
Review comments addressed.
Added `addComponentsAndExpand` API and tests.
I decided to override the Javadocs on HL/VL to mention that calling `addComponentsAndExpand` also sets width/height to 100% if not previously defined.

2021-09-17 11:32 UTC, DiegoCardoso commented on vaadin-legacy-components-flow-integration-tests/src/main/java/com/vaadin/legacy/ui/examples/layout/layouttester/ExpandRatioView.java
> +                "Set expand ratio (one)",
Bad c/p. Fixed.

2021-09-17 11:32 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/test/java/com/vaadin/legacy/ui/AbstractOrderedLayoutTest.java
> +
Added tests for removing element with expand ratio defined.

2021-09-17 11:44 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            setExpandRatio(component, 1);
But the child component should also get 100 % width / height ?

2021-09-17 11:44 UTC, pleku commented on vaadin-legacy-components-flow/src/test/java/com/vaadin/legacy/ui/AbstractOrderedLayoutTest.java
> +    public void setExpandRatio_shouldRecalculate_elementWithExpandRatioIsRemoved() {
nit: should be _given when then_, this reads to me as _given then when_
same for other added tests

2021-09-17 11:46 UTC, pleku requested changes

2021-09-17 11:46 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            setWidth(100, Unit.PERCENTAGE);
The existing code checks for undefined w/h and only then sets it to 100 %, why change this ?

2021-09-17 12:59 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            setWidth(100, Unit.PERCENTAGE);
But, isn't it the same that this code is doing?
- Check if it's vertical
  - if so, check if height is undefined and then set it 100%
- if not vertical, check if width is undefined and then set it 100%

2021-09-17 13:38 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            setWidth(100, Unit.PERCENTAGE);
Correct - I don't know what I was looking at

2021-09-17 14:04 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            setExpandRatio(component, 1);
That's correct. For a moment I thought that was referring to the slot. Now it's fixed. The code looks rather ugly, because I needed to cast to `HasSize` or `Sizeable` in order to call `setWidth`/`setHeight`.

2021-09-17 14:04 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/test/java/com/vaadin/legacy/ui/AbstractOrderedLayoutTest.java
> +    public void setExpandRatio_shouldRecalculate_elementWithExpandRatioIsRemoved() {
Fixed method names.

2021-09-20 07:07 UTC, pleku approved these changes

2021-09-20 08:10 UTC, merged