add more AOL methods
vaadin/flow-legacy-components pull request #54
Opened 2021-09-16 10:35 UTC by fhdhsni

fixes #10

2021-09-16 10:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow-legacy-components?pullRequest=54) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow-legacy-components?pullRequest=54) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow-legacy-components?pullRequest=54) it.</sub>

2021-09-16 18:54 UTC, pleku requested changes
Reviewed implementation; unit tests still TODO

2021-09-16 18:54 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        boolean isChildComponent = component.getParent().orElse(null) == this;
This can be replaced by the `isChild` method instead when it is added by expand ratio PR

2021-09-16 18:54 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        if (isChildComponent) {
As `Node::insertChild` already takes care of retaining order when moving an existing child, I'm wondering if this could be simplified with something like
```java
movingChildrenInternally = true;
container.insertChild(insertPosition, slot);
movingChildrenInternally = false;
if (spacing) {
  container.insertChild(adjustedSpacingIndex, existingSpacingElement);
}
```
where
- `insertPosition` is basically the given `index` with taken the spacing elements into account (index*2)
- `existingSpacingElement` is the next element after the slot (or previous if it was last)
- `adjustedSpacingIndex` is `insertPosition + 1` or `insertPosition -1` if it is moved as last

Or am I just being naïve and need to take a look at this with fresh eyes 🤔

2021-09-16 18:54 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        movingChildrenInternally = true;
I was first wondering that how can `movingChildrenInternally` actually happen here, but I now realize as the variable naming doesn't fit that well into this case anymore. I was thinking how to rename it, but then I actually realized that you're using the wrong variable.  `movingChildrenInternally` could be renamed to `ignoreElementDetachEvents` and that cannot be used here - you should be using `removingChildrenInternally` instead as it then the detach listener is cleared for the removed component. Otherwise we'll leak memory as the listener stays on the component and it has references to this layout.

2021-09-16 18:54 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        movingChildrenInternally = true;
Looking at the old FW implementation, I'm wondering if the simple but verbose logic could be c/p and adjusted to reduce regression risk?

2021-09-17 13:38 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            throw new IndexOutOfBoundsException();
yeah that makes more sense in this case, but that's what FW is throwing.

2021-09-17 13:39 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            if (currentIdxOfComponent == index) {
moved up, done.

2021-09-17 13:43 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        if (isChildComponent) {
You mean something like this?
```
if (isChild(component)) {
    if (getComponentIndex(component) == index) {
        return;
    }

    slot = component.getElement().getParent();
    int slotIdx = container.indexOfChild(slot);

    int insertionPosition = index;
    if(isSpacing()) {
        insertionPosition = index * 2;
    }

    Element existingSpacingElement = null;
    if(isSpacing()) {
        if(slotIdx == container.getChildCount() - 1) {
            existingSpacingElement = container.getChild(slotIdx - 1);
        } else {
            existingSpacingElement = container.getChild(slotIdx + 1);
        }
    }

    movingChildrenInternally = true;
    container.insertChild(insertionPosition, slot);
    movingChildrenInternally = false;
    if(existingSpacingElement != null) {
        int adjustedSpacingIndex = insertionPosition;
        adjustedSpacingIndex = adjustedSpacingIndex == 0 ? 1 : adjustedSpacingIndex - 1;

        container.insertChild(adjustedSpacingIndex,existingSpacingElement);
    }

} else { ... }
```
If so, I don't think that's much simpler :)
And with that 👆implementation [this test](https://github.com/vaadin/flow-legacy-components/blob/feat-10/vaadin-legacy-components-flow/src/test/java/com/vaadin/legacy/ui/AbstractOrderedLayoutTest.java#L709-L710) is failing.
Anyway if you think this is a better solution I can put more time into it to make it work.

2021-09-17 13:50 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        movingChildrenInternally = true;
Yeah `movingChildrenInternally` should only be used in the case of swapping here.
Simplified it a bit. take a look and if you think it's not good, I'll try to adopt the FW solution.

2021-09-17 15:01 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            throw new IndexOutOfBoundsException();
I couldn't find it throwing this on FW.

2021-09-20 08:07 UTC, pleku requested changes

2021-09-20 08:36 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            throw new IndexOutOfBoundsException();
FW is using a `LinkedList` to store the components which throws `IndexOutOfBoundsException` in those scenarios.

2021-09-20 08:41 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        if (isChildComponent) {
I think we can proceed with this and this bit can be refactored later on if needbe

2021-09-20 08:42 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        movingChildrenInternally = true;
Saul Goodman

2021-09-20 08:58 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            container.insertChild(slotIdx, createSpacing());
Yeah needed to fix #59 and #45 in this PR as well.

Now that we removing the dangling spacing element (#59), when adding an existing component it removes the valid `v-spacing` that we just added (`cleanupSlotsAndSpacing` is triggered when you add an existing child). But with these changes, that is not a problem because we add the `v-spacing` before the added slot, after we append it.

2021-09-20 09:05 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            container.insertChild(slotIdx, createSpacing());
Please document that rationing in the code as it is far from obvious

2021-09-20 10:08 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        }
done

2021-09-20 10:09 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            container.insertChild(slotIdx, createSpacing());
added a comment, see if it's enough or need a better wording.

2021-09-20 10:33 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        boolean isChildComponent = component.getParent().orElse(null) == this;
done

2021-09-20 12:57 UTC, pleku requested changes

2021-09-20 12:57 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            movingChildrenInternally = false;
Just noting that this is still not done. As `markAsDirtyRecursive` is not needed (children stay the same), so `writeChildCustomStylesToSlots()` needs to be called before returning here.

2021-09-20 12:57 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        }
This method is lacking `markAsDirtyRecursive` at the end

2021-09-20 13:43 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            movingChildrenInternally = false;
done

2021-09-20 13:43 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        }
done

2021-09-21 05:45 UTC, pleku approved these changes

2021-09-21 05:47 UTC, merged

2021-09-21 07:17 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            container.insertChild(slotIdx, createSpacing());
I've just reverted this change while doing #48 as the proper logic for an existing child is to _remove it_  and then the clean-up logic does not need to be duplicated, complicating the adding logic. Like it has been done with the FW.