add alignment methods
vaadin/flow-legacy-components pull request #64
Opened 2021-09-21 10:04 UTC by fhdhsni

fixes #20

2021-09-22 05:19 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        setAlignmentToSlots();
combining these two methods to sth like `setSlotClasses()`?
```
writeChildCustomStylesToSlots();
setAlignmentToSlots();
```

2021-09-22 11:29 UTC, DiegoCardoso requested changes
First few comments. I will check the tests now.
Got a bit confused with `Alignment` vs `AlignmentInfo` classes, but that's how FW is doing stuff so  ¯\_(ツ)_/¯

2021-09-22 11:29 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Alignment.java
> +}
nit: new line

2021-09-22 11:29 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/resources/META-INF/frontend/ordered-layout.css
> +    justify-content: flex-end;
I think we can change it to `right` and on `.v-slot` to `left` to avoid issues with RTL.

2021-09-22 13:30 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        ComponentUtil.setData(childComponent, Alignment.class, alignment);
done

2021-09-22 13:30 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Alignment.java
> +}
done

2021-09-22 13:30 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/resources/META-INF/frontend/ordered-layout.css
> +    justify-content: flex-end;
done

2021-09-22 13:36 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        setAlignmentToSlots();
The reason I asked is that `writeChildCustomStylesToSlots` sets the `class` attribute, removing all the existing classes. So swapping those lines removes that alignment classes (have a test to prevent that).

2021-09-22 13:56 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        setAlignmentToSlots();
Hmm, I see it now. 

Giving an extra thought over this, there might be a benefit from merging the methods which is to avoid looping through the same children twice. Maybe it's better to make it in one pass.

2021-09-23 06:49 UTC, pleku requested changes

2021-09-23 06:49 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        setAlignmentToSlots();
Seems like a good idea to loop once and mayhaps keep the individual operations in their own method

2021-09-23 06:49 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        markAsDirtyRecursive();
This doesn't seem right, why is it added ? Seems like a weird thing that is just dropped there to workaround some other issue ? Ok, it seems like it was moved from the end of the method instead to workaround another issue ... lets merge #65 first then as it fixes things

2021-09-23 06:49 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            setComponentAlignment(component, getDefaultComponentAlignment());
I'd suggest merging #65 first as it fixes things 👀

2021-09-23 06:49 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +    private static class AlignmentKey {
Please don't mix inner classes in the middle of methods, move either to bottom or to the end

2021-09-23 06:49 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            }
```suggestion
            classList.set(ALIGN_CLASS_PREFIX + "center", alignment.isHorizontalCenter());
            classList.set(ALIGN_CLASS_PREFIX + "right", alignment.isRight());
```

2021-09-23 06:49 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            }
```suggestion
            classList.set(ALIGN_CLASS_PREFIX + "middle", alignment.isVerticalCenter());
            classList.set(ALIGN_CLASS_PREFIX + "bottom", alignment.isBottom());
```

2021-09-23 08:01 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +    private static class AlignmentKey {
done

2021-09-23 08:01 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            }
done

2021-09-23 08:01 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            }
done

2021-09-23 08:01 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +            setComponentAlignment(component, getDefaultComponentAlignment());
👍

2021-09-23 08:02 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        markAsDirtyRecursive();
put it there because `even if not moving the component it should get the default alignment`. ain't necessary anymore, with the new changes

2021-09-23 08:03 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        setAlignmentToSlots();
merged to one method, named it `setSlotClasses`

2021-09-23 08:14 UTC, pleku requested changes

2021-09-23 08:14 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        // it would be even necessary
This comment is in the wrong place now; it should be before the if-check
Please move it there so that the context stays correct instead of potentially confusing

2021-09-23 08:14 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
>          final String ALIGN_CLASS_PREFIX = "v-align-";
Nit: this is effectively a constant so could just make it so

2021-09-23 08:21 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        // it would be even necessary
🤦‍♂️ fixed

2021-09-23 08:22 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
>          final String ALIGN_CLASS_PREFIX = "v-align-";
done

2021-09-23 08:38 UTC, pleku approved these changes

2021-09-23 08:51 UTC, DiegoCardoso approved these changes

2021-09-23 08:51 UTC, merged