feat: add margin API
vaadin/flow-legacy-components pull request #66
Opened 2021-09-21 13:10 UTC by DiegoCardoso

## Description

- Add `Layout` and `Layout.MarginHandler` interfaces
- Copy/paste `MarginInfo` class from FW, removing `@Deprecated` methods
- Make `AbstractOrderedLayout` implement `Layout.MarginHandler`
- Add unit tests to ensure that CSS classes are being added accordingly
- Add CSS file defining the style used by the feature and make VL/HL import it 

Fixes #40 

## Type of change

- [ ] Bugfix
- [X] Feature

2021-09-21 13:21 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/MarginInfo.java
> +     * @since 7.5.0
All `since`s should be just removed

2021-09-21 13:23 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/VerticalLayout.java
>          super(true);
Where is the `setMargin(true)` ?

2021-09-21 13:46 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/MarginInfo.java
> +     * @since 7.5.0
Removed.

2021-09-21 13:46 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Layout.java
> +public interface Layout extends ComponentContainer {
Added.

2021-09-21 13:46 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/VerticalLayout.java
>          super(true);
My bad. Forgot to mention the defaults on FW. Added.

2021-09-22 07:05 UTC, fhdhsni requested changes

2021-09-22 09:29 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractOrderedLayout.java
> +        return marginInfo;
Fixed.

2021-09-22 13:55 UTC, fhdhsni approved these changes

2021-09-23 06:02 UTC, pleku approved these changes

2021-09-23 06:03 UTC, merged