feat: add Label component
vaadin/flow-legacy-components pull request #91
Opened 2021-10-04 06:52 UTC by fhdhsni

fixes: #75

2021-10-04 06:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow-legacy-components?pullRequest=91) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow-legacy-components?pullRequest=91) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: fhdhsni<br/>:x: anezthes<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow-legacy-components?pullRequest=91) it.</sub>

2021-10-04 13:33 UTC, pleku requested changes

2021-10-04 13:33 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Label.java
> +        getElement().getStyle().set("display", "contents");
Controlling the `display` property from Java has one side effect - it makes it possible for the user to accidentally break the component by doing something silly through the element API. Thus it might be feasible to use another way to specify the caption on/off effect to the `display` CSS value that cannot be overridden, like through css that is triggered by some internal class name or attribute in DOM and forces the style with `!important`. Or maybe it would be just enough to add `!important` here ?

2021-10-04 13:33 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Label.java
> +        vCaption.setAttribute("for", getId().get());
I don't get why the ID must be set explicitly - mind dropping a comment for that ?

2021-10-04 13:33 UTC, pleku commented on vaadin-legacy-components-flow-demo/src/main/java/com/vaadin/legacy/ui/demo/LabelWidgetView.java
> +    protected void initView() {
What about content mode demo ?

2021-10-04 13:33 UTC, pleku commented on vaadin-legacy-components-flow-demo/src/main/java/com/vaadin/legacy/ui/demo/LabelWidgetView.java
> +        Label h1 = new Label("Labels");
What about caption demo ?

2021-10-05 08:50 UTC, fhdhsni commented on vaadin-legacy-components-flow/pom.xml
> +            <version>1.14.2</version>
removed it.

2021-10-05 08:50 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractComponent.java
> +     * is executed when a style name is added or removed, mainly used to mark
fixed.

2021-10-05 08:50 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/ValoTheme.java
> +public class ValoTheme {
take a look. not sure if it's correct/enough

2021-10-05 08:50 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/ValoTheme.java
> +package com.vaadin.legacy.ui;
We copied it from the flow-components and it was this way there. Most of the files are currently like this. Some of the files are using a wrong licence I think (e.g `SingleComponentContainer`). I'll create a ticket to align all the files to one style and one licence.

2021-10-05 08:50 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/ValoTheme.java
> +     * Panel styles
removed them, can be added later.

2021-10-05 08:50 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Label.java
> +@JsModule("@vaadin/vaadin-lumo-styles/font-icons.js")
done.

2021-10-05 08:50 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/test/java/com/vaadin/legacy/ui/AbstractComponentTest.java
> +    public void shouldReturnInternalStyles() {
done.

2021-10-05 08:51 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Label.java
> +        getElement().setAttribute("class",
done

2021-10-05 08:51 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Label.java
> +        if (this.caption != null && this.caption.equals(caption)) {
done.

2021-10-05 08:51 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Label.java
> +    // tested
oops, sorry, forgot to remove them.

2021-10-05 08:51 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Label.java
> +        getElement().removeChild(vCaption);
no it's not possible (otherwise it's a bug).
inlined the method.

2021-10-05 08:51 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Label.java
> +        getElement().getStyle().set("display", "contents");
Can't think of a way to make it more private. Adding `!important` makes it a bit more stronger but can't do that because of vaadin/flow#11981. I'll leave it as is for now.

2021-10-05 08:51 UTC, fhdhsni commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Label.java
> +        vCaption.setAttribute("for", getId().get());
added a comment.

2021-10-05 08:51 UTC, fhdhsni commented on vaadin-legacy-components-flow-demo/src/main/java/com/vaadin/legacy/ui/demo/LabelWidgetView.java
> +    protected void initView() {
added a `ContentMode.PREFORMATTED` demo. There's one already for `ContentMode.HTML`

2021-10-05 08:51 UTC, fhdhsni commented on vaadin-legacy-components-flow-demo/src/main/java/com/vaadin/legacy/ui/demo/LabelWidgetView.java
> +        Label h1 = new Label("Labels");
added an example for caption as html.

2021-10-05 09:24 UTC, pleku approved these changes

2021-10-05 11:06 UTC, DiegoCardoso approved these changes

2021-10-06 08:47 UTC, merged