feat: implement Panel component
vaadin/flow-legacy-components pull request #93
Opened 2021-10-04 15:12 UTC by DiegoCardoso

## Description

Add `Panel` element implementing `AbstractSingleComponentContainer`.

List of changes:
- Add internal components using the `Element` API, so it won't be accessible through the `Component` APIs
- Change `AbstractSingleComponentContainer` to allow a subclass to define the element wrapper for the content
- Make sure that custom styles added to `Panel` are applied properly to inner elements (caption and scrollable)
- Use scroll event listener with debouncer to synchronize the scroll position on the server

Fixes # $28

## Type of change

- [ ] Bugfix
- [X] Feature

#### Additional for `Feature` type of change

- [X] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

2021-10-04 15:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/flow-legacy-components?pullRequest=93) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/flow-legacy-components?pullRequest=93) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: DiegoCardoso<br/>:x: anezthes<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/flow-legacy-components?pullRequest=93) it.</sub>

2021-10-04 15:28 UTC, DiegoCardoso commented
Javadoc is missing. Will add them tomorrow.

2021-10-05 09:17 UTC, pleku requested changes

2021-10-05 09:17 UTC, pleku commented on vaadin-legacy-components-flow/src/main/resources/META-INF/frontend/panel.css
> +    padding: 0.25em;
Should this be affected by `lumo-space` too as the caption itself is ?

2021-10-05 09:17 UTC, pleku commented on vaadin-legacy-components-flow/src/main/resources/META-INF/frontend/panel.css
> +.v-panel-caption vaadin-icon {
This will only work if the set icon is a `vaadin-icon` - should there be some style name that is applied to the given `Icon` that can be targeted instead ? If someone e.g. sets font awesome icon there

2021-10-05 09:17 UTC, pleku commented on vaadin-legacy-components-flow/src/test/java/com/vaadin/legacy/ui/PanelTest.java
> +    public void newPanel_testDOMStructure() {
Don't see how this tests the structure if it doesn't even check the child elements

2021-10-05 09:17 UTC, pleku commented on vaadin-legacy-components-flow/pom.xml
> +            <artifactId>flow-html-components</artifactId>
Why ? It is even a duplicate from above in the file

2021-10-05 09:17 UTC, pleku commented on vaadin-legacy-components-flow/pom.xml
> +            <version>22.0-SNAPSHOT</version>
I don't get it - why are these dependencies introduced at this level ?

2021-10-05 09:17 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractSingleComponentContainer.java
> +    protected void setContentWrapper(Element wrapper) {
I don't like this, but I don't have a good suggestion to replace it with.

2021-10-05 09:17 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractSingleComponentContainer.java
> +            getElement().appendChild(wrapper);
Since this method gives the impression that it can be called again, changing the wrapper leaves the old content inside the old wrapper.

2021-10-05 12:18 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Panel.java
> +                .debounce(300).addEventData("element.scrollTop")
Do you mean the debounce value?

2021-10-05 13:00 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractSingleComponentContainer.java
> +            getElement().appendChild(wrapper);
I can make it simpler by allowing it to be called only once and only if not content is added to the container. That way, if the container needs to define a wrapper, then it must set it before the content is set. WDYT?

2021-10-05 15:40 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractSingleComponentContainer.java
> +            getElement().appendChild(wrapper);
That would at least prevent bugs and possible _wtf_s as the current code seems a bit smelly.
Another alternative would be to introduce an abstract method which creates the wrapper once, but calling overridden methods from constructor should not be done either

2021-10-05 15:40 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Panel.java
> +                .debounce(300).addEventData("element.scrollTop")
Yes

2021-10-05 15:41 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/Panel.java
> +                .debounce(300).addEventData("element.scrollTop")
Also I don't understand how it is not a feature of the scroller component but that is another thing

2021-10-05 15:43 UTC, pleku commented on vaadin-legacy-components-flow/src/main/java/com/vaadin/legacy/ui/AbstractSingleComponentContainer.java
> +    protected Element getContentWrapper() {
Protected methods still missing javadocs

2021-10-05 15:47 UTC, pleku commented on vaadin-legacy-components-flow/pom.xml
> +            <version>22.0-SNAPSHOT</version>
Right - scroller comes from ordered layout package

2021-10-05 15:52 UTC, pleku requested changes
I see that you force pushed and made me look at everything again 😿

2021-10-05 15:53 UTC, DiegoCardoso commented on vaadin-legacy-components-flow/src/test/java/com/vaadin/legacy/ui/PanelTest.java
> +    public void newPanel_testDOMStructure() {
Done.

2021-10-05 15:53 UTC, DiegoCardoso commented on vaadin-legacy-components-flow-demo/src/main/java/com/vaadin/legacy/ui/demo/LegacyComponentsView.java
> +import com.vaadin.legacy.ui.Panel;
Removed.

2021-10-05 15:55 UTC, DiegoCardoso commented
That's weird. I thought I had made a normal push through GH cli 🤔

2021-10-06 08:28 UTC, pleku approved these changes

2021-10-06 11:30 UTC, fhdhsni approved these changes

2021-10-06 11:48 UTC, merged